export const H2 = {
    margin: "0 0 14px",
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: "-0.04em",
    color: "#0f172a",
    fontFamily: "'Manrope', 'Inter', 'Noto Sans SC', sans-serif",
};

export const sectionTitle = {
    fontSize: 11,
    fontWeight: 800,
    marginBottom: 12,
    color: "#64748b",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
};

export const emptyText = {
    fontSize: 12,
    color: "#94a3b8",
    textAlign: "center",
    padding: "14px 0",
    lineHeight: 1.7,
};

export const listRow = {
    display: "flex",
    justifyContent: "space-between",
    gap: 14,
    alignItems: "center",
    padding: "14px 0",
};

export const S = {
    root: {
        minHeight: "100vh",
        background: "radial-gradient(circle at top left, rgba(221,232,255,0.78), transparent 22%), radial-gradient(circle at top right, rgba(255,233,220,0.62), transparent 20%), linear-gradient(180deg, #f8faff 0%, #f3f6fb 45%, #eef2f8 100%)",
        fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
        color: "#1f2937",
    },
    header: {
        position: "sticky",
        top: 0,
        zIndex: 30,
        background: "rgba(248, 250, 255, 0.78)",
        backdropFilter: "blur(16px)",
        borderBottom: "1px solid rgba(148,163,184,0.14)",
        padding: "20px 28px 16px 292px",
    },
    headerInner: {
        maxWidth: 1220,
        margin: "0 auto",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 18,
        flexWrap: "wrap",
    },
    kicker: {
        margin: 0,
        fontSize: 10,
        fontWeight: 800,
        letterSpacing: "0.22em",
        color: "rgba(51,65,85,0.44)",
        textTransform: "uppercase",
    },
    title: {
        margin: "6px 0 0",
        fontSize: 32,
        lineHeight: 1.05,
        fontWeight: 800,
        letterSpacing: "-0.05em",
        fontFamily: "'Manrope', 'Inter', 'Noto Sans SC', sans-serif",
        color: "#0f172a",
    },
    subtitle: {
        margin: "8px 0 0",
        fontSize: 11,
        color: "rgba(51,65,85,0.54)",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
    },
    statusPill: {
        display: "inline-flex",
        alignItems: "center",
        gap: 10,
        padding: "10px 16px",
        borderRadius: 999,
        background: "rgba(255,255,255,0.76)",
        color: "#475569",
        fontSize: 10,
        fontWeight: 800,
        letterSpacing: "0.18em",
        boxShadow: "0 10px 24px rgba(51,65,85,0.08), inset 0 0 0 1px rgba(255,255,255,0.72)",
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 999,
        background: "#22c55e",
        display: "inline-block",
        boxShadow: "0 0 0 6px rgba(34,197,94,0.12)",
    },
    statsRow: {
        display: "flex",
        gap: 10,
        flexWrap: "wrap",
    },
    main: {
        marginLeft: 256,
        width: "calc(100vw - 256px)",
        maxWidth: "calc(100vw - 256px)",
        padding: "24px 28px 72px",
        minHeight: "calc(100vh - 110px)",
    },
    nav: {
        position: "fixed",
        left: 16,
        top: 16,
        bottom: 16,
        width: 224,
        background: "linear-gradient(180deg, rgba(15,23,42,0.97), rgba(28,37,64,0.95))",
        borderRadius: 28,
        padding: "24px 14px 18px",
        zIndex: 40,
        display: "flex",
        flexDirection: "column",
        gap: 24,
        boxShadow: "0 28px 60px rgba(15,23,42,0.26)",
        border: "1px solid rgba(255,255,255,0.08)",
    },
    sidebarTop: {
        padding: "4px 16px 12px",
    },
    sidebarBrand: {
        fontFamily: "'Manrope', 'Inter', 'Noto Sans SC', sans-serif",
        fontSize: 18,
        lineHeight: 1.3,
        fontWeight: 800,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        color: "#f8fbff",
    },
    sidebarCaption: {
        marginTop: 10,
        fontSize: 10,
        color: "rgba(226,232,240,0.44)",
        letterSpacing: "0.22em",
        textTransform: "uppercase",
    },
    navInner: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        gap: 8,
        padding: "0 2px",
    },
    navBtn: {
        width: "100%",
        background: "none",
        border: "none",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-start",
        gap: 12,
        padding: "14px 16px",
        position: "relative",
        fontFamily: "inherit",
        borderRadius: 18,
        textAlign: "left",
        transition: "all .18s ease",
    },
    dotBadge: {
        position: "absolute",
        top: "50%",
        right: 12,
        transform: "translateY(-50%)",
        minWidth: 20,
        height: 20,
        borderRadius: 999,
        background: "#ffffff",
        color: "#0f172a",
        fontSize: 10,
        fontWeight: 800,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "0 6px",
    },
    sidebarFooter: {
        marginTop: "auto",
        padding: "0 10px",
    },
    footerPill: {
        background: "linear-gradient(135deg, rgba(255,255,255,0.16), rgba(255,255,255,0.08))",
        color: "#f8fafc",
        borderRadius: 18,
        padding: "14px 16px",
        fontSize: 11,
        fontWeight: 700,
        letterSpacing: "0.08em",
        textAlign: "center",
        boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.08)",
        lineHeight: 1.6,
    },
};
