import { H2, sectionTitle, emptyText, listRow } from "./commonStyles";

export { H2, sectionTitle, emptyText, listRow };

export const S = {
    root: {
        minHeight: "100vh",
        background: "#f9f9f9",
        color: "#111111",
    },
    header: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        height: 72,
        zIndex: 20,
        background: "rgba(249,249,249,0.96)",
        borderBottom: "1px solid rgba(198,198,198,0.2)",
        backdropFilter: "blur(8px)",
    },
    headerInner: {
        maxWidth: 1280,
        margin: "0 auto",
        padding: "10px 24px",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    title: {
        margin: 0,
        fontSize: 18,
        fontWeight: 800,
    },
    subtitle: {
        margin: 0,
        fontSize: 11,
        color: "#6b7280",
    },
    nav: {
        position: "fixed",
        left: 0,
        top: 72,
        bottom: 0,
        width: 160,
        padding: 12,
        borderRight: "1px solid rgba(198,198,198,0.2)",
        background: "#f9f9f9",
        zIndex: 10,
    },
    sidebarTop: {
        marginBottom: 12,
        padding: "6px 8px",
    },
    sidebarBrand: {
        fontSize: 11,
        color: "#6b7280",
        letterSpacing: "0.03em",
        fontWeight: 700,
    },
    navInner: {
        display: "flex",
        flexDirection: "column",
        gap: 6,
    },
    navBtn: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        border: "none",
        width: "100%",
        borderRadius: 10,
        padding: "9px 10px",
        cursor: "pointer",
        fontFamily: "inherit",
    },
    dotBadge: {
        minWidth: 18,
        height: 18,
        borderRadius: 999,
        background: "#111111",
        color: "#fff",
        fontSize: 10,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "0 6px",
    },
    main: {
        position: "fixed",
        left: 160,
        right: 0,
        top: 72,
        bottom: 0,
        padding: 16,
        overflow: "hidden",
    },
    content: {
        height: "100%",
        maxWidth: 1280,
        margin: "0 auto",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
        gap: 12,
    },
};
